version: 2.1
orbs:
  heroku: circleci/heroku@1.2.5
  
jobs:
  test:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run:
          name: Pull Submodules
          command: |
            git submodule init
            git submodule update --remote
      - run:
          name: Install deps
          command: sudo make dev-install
      - run:
          name: Linting
          command: make format-check
      - run:
          name: Run tests
          command: make test

  deploy:
    machine:
      image: ubuntu-1604:201903-01 # https://circleci.com/docs/2.0/configuration-reference/#available-machine-images with Docker 18.09.3
    steps:
      - checkout

workflows:
  version: 2
  test-and-deploy:
    jobs:
      - test
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: 
                - master
                - staging
  weekly:
    jobs:
      - test
      - deploy:
          requires:
            - test
    triggers:
      - schedule:
          cron: "0 0 * * 1"
          filters:
            branches:
              only:
                - staging
