version: 2.1

orbs:
  heroku: circleci/heroku@1.2.5

jobs:
  test:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run:
          name: Pull Submodules
          command: |
            git submodule init
            git submodule update --remote
      - run:
          name: Install deps
          command: sudo make dev-install
      - run:
          name: Linting
          command: make format-check
      - run:
          name: Run tests
          command: make test

workflows:
  version: 2
  test-and-deploy:
    jobs:
      - test
      - heroku/deploy-via-git:
          requires:
            - test
          post-steps:
          - run: 
              name: Run tests
              command: make docker-setup
          filters:
            branches:
              only: 
                - master
                - staging
  weekly:
    jobs:
      - test
      - heroku/deploy-via-git:
          requires:
            - test
          post-steps:
          - run: 
              name: Run tests
              command: make docker-setup
    triggers:
      - schedule:
          cron: "0 0 * * 1"
          filters:
            branches:
              only:
                - staging
